- volatility/framework/automagic/symbol_cache.py
Just like in https://github.com/volatilityfoundation/volatility3/blob/master/volatility/framework/symbols/windows/pdbconv.py#L921
> Check progress_callback is not None before call

- volatility/framework/layers/elf.py
- volatility/framework/symbols/linux/elf.json
Ok, this seems to have stabilized and seems to be working ok.  It should resolve issue #97.  I'd appreciate some eyes on it, particularly those that worked with the previous incarnation.  Let's go with another 7 days, so if I don't hear anything then I'll merge this on the 3rd November.  5:)
> Elf64 support

- README.md
If it can be markdown, it will be markdown! This _should_ all be compliant.
Also includes #90.
On @ikelos' advice, I've left the email address alone.
Happy to change whatever.
> Markdown all the things

- volatility/cli/__init__.py
- volatility/framework/constants/__init__.py
- volatility/framework/exceptions.py
- volatility/framework/interfaces/symbols.py
- volatility/framework/objects/templates.py
- volatility/framework/plugins/windows/virtmap.py
- volatility/framework/symbols/__init__.py
- volatility/framework/symbols/intermed.py
Ensure that if an exception gets thrown and not caught, that it's displayed to the user in the CLI with appropriate suggestions.
I'm reasonably happy with how this is laid out, and the other improvements to exceptions.  @atcuno I know you were interested in ensuring suitable warnings, please take a look at this.  I'll merge it by the 14th (so, after our next meeting) if I haven't had any feedback...  5:)
> Issue109 standardized exceptions

- volatility/cli/__init__.py
- volatility/framework/configuration/requirements.py
- volatility/framework/contexts/__init__.py
- volatility/framework/interfaces/automagic.py
- volatility/framework/layers/msf.py
- volatility/framework/layers/physical.py
- volatility/framework/layers/vmware.py
- volatility/framework/objects/__init__.py
- volatility/framework/plugins/windows/poolscanner.py
- volatility/framework/plugins/windows/verinfo.py
- volatility/framework/renderers/__init__.py
- volatility/framework/symbols/__init__.py
- volatility/framework/symbols/intermed.py
- volatility/framework/symbols/windows/extensions/services.py
- volatility/framework/symbols/windows/pdbconv.py
Hiya, here's my attempt at going through all the exceptions we throw.  Note, this is just fixing up the exceptions and explicitly does not change any that we catch, so if you see one that you expect to get caught but doesn't, please shout.
Also if there's any you disagree with, or don't think are worthwhile) or any I've missed, please shout too...  5:)
I'm a little nervous about making a change of this size with potentially subtle and difficult to spot issues, so this is likely to go into 3.0.0_beta2, but still worth reviewing/checking if you can.  5:)
> Tidy up exceptions to be more accurate.

- volatility/framework/interfaces/layers.py
Previously, for segmented layers, no chunk larger than a full segment
was scanned.  Now, we combine contiguous segments up to
scanner.chunk_size (or until a non-present segment) in order to scan it.
This may be slightly slower (by concatting the data together) but gives
results of hits across page boundaries (the point of the scanning
capability), whereas previously each page was scanned individually.
> layers: Improve scanning of layered chunks

- volatility/__init__.py
- volatility/framework/automagic/mac.py
- volatility/framework/automagic/symbol_cache.py
- volatility/framework/configuration/requirements.py
- volatility/framework/interfaces/configuration.py
- volatility/framework/interfaces/layers.py
- volatility/framework/interfaces/renderers.py
- volatility/framework/interfaces/symbols.py
- volatility/framework/layers/elf.py
- volatility/framework/layers/scanners/__init__.py
- volatility/framework/layers/scanners/multiregexp.py
- volatility/framework/plugins/windows/handles.py
- volatility/framework/plugins/windows/poolscanner.py
- volatility/framework/plugins/windows/registry/printkey.py
- volatility/framework/plugins/windows/virtmap.py
- volatility/framework/renderers/__init__.py
- volatility/framework/symbols/intermed.py
- volatility/framework/symbols/windows/extensions/__init__.py
A bunch of slight type improvements.  They're split up into chunks for simpler review/bisection.  They should preeminently be neutral (affecting only types in a non-code changing way).
Where the code has changed, it's often to maneuver the type checks so that mypy can make inferences about the type involved.
I'll commit this on the 27th if nothing crops up...
> Typing improvements

- volatility/framework/symbols/windows/pdbconv.py
Previously we allow name-collisions for types with name <anonymouos-tag>
so this has now been resolved, as well as descending too deeply down the
type to tree determine the size of array occasionally.
Another reasonably deep fix, but quite straight forward.  It will eventually require regeneration of all the windows symbol tables, but using the previous ones should have minimal impact (they're usually deeply down a type tree, and for a type that wasn't given a name).
No timeline set on this one (although, probably a month mebbe?) because things this foundational make me want them checked more than I want them committed...  5:)
> pdbconv: Avoid more name-collisions

- volatility/framework/layers/resources.py
Refactoring should be straight forward (I don't think there's any side effects of the reshuffling inside the code), but it now makes the termination conditions a little more explicit and simpler to reason about.
I'll be committing this on the 11th if no one raises a reason not to.  5:)
> Layers: Remove (horrible, horrible) uses of while true in the codebase (my bad)

- volatility/framework/plugins/windows/procdump.py
@ikelos can you check it please? and any suggestion on process dump proc description as we had in vad_dump?
> expose process_dump to other plugins

- volatility/framework/symbols/windows/extensions/pe.py
Just taking a look at the procdump code (with a view towards rebuild EXEs rather than just memory) and it seemed as though we went through the list twice, without overly good reason?  `VirtualSize` seems like a reasonable way of determining how big the section should be, rather than doing a weird dance of figuring out the difference between the previous section and the next section?
As such, I've hopefully condensed this down into a single loop through, but I'm really not sure why we do it this way, so I'm nervous about doing the update.
Technically the `VirtualSize` could end up being huge (so mebbe we should have a max limit)?  Also, rounding up could make it stretch outside of its bounds, but since they're layered in order, new sections will start at their correct offset, so there …
> Procdump: Don't loop through twice without good reason.

- volatility/framework/symbols/intermed.py
- volatility/schemas/schema-6.2.0.json
Add in support for flatten anonymous, and whilst adding the new schema solidify what information is and isn't allowed in the linux/mac metadata areas.
Resolves #151
> Issue151 flatten anonymous

- volatility/framework/plugins/windows/driverirp.py
- volatility/framework/plugins/windows/driverscan.py
- volatility/framework/plugins/windows/handles.py
- volatility/framework/plugins/windows/mutantscan.py
- volatility/framework/plugins/windows/symlinkscan.py
- volatility/framework/symbols/windows/extensions/__init__.py
- volatility/framework/symbols/windows/extensions/pool.py
This replaces https://github.com/volatilityfoundation/volatility3/pull/230
> refs #200 raise ValueError if an object doesn't have a name

- volatility/cli/__init__.py
> Added instructions for help on a plugin

- volatility/framework/symbols/mac/extensions/__init__.py
> Issue #202 - Check for invalid vnode pointers before processing path

- doc/source/simple-plugin.rst
- volatility/framework/plugins/linux/bash.py
- volatility/framework/plugins/linux/elfs.py
- volatility/framework/plugins/linux/lsof.py
- volatility/framework/plugins/linux/malfind.py
- volatility/framework/plugins/linux/proc.py
- volatility/framework/plugins/linux/pslist.py
- volatility/framework/plugins/mac/bash.py
- volatility/framework/plugins/mac/lsof.py
- volatility/framework/plugins/mac/malfind.py
- volatility/framework/plugins/mac/netstat.py
- volatility/framework/plugins/mac/proc_maps.py
- volatility/framework/plugins/mac/psaux.py
- volatility/framework/plugins/mac/pslist.py
- volatility/framework/plugins/windows/cmdline.py
- volatility/framework/plugins/windows/dlldump.py
- volatility/framework/plugins/windows/dlllist.py
- volatility/framework/plugins/windows/handles.py
- volatility/framework/plugins/windows/malfind.py
- volatility/framework/plugins/windows/procdump.py
- volatility/framework/plugins/windows/pslist.py
- volatility/framework/plugins/windows/vaddump.py
- volatility/framework/plugins/windows/vadinfo.py
- volatility/framework/plugins/windows/vadyarascan.py
Now that we've got List parameters working as expected in the CLI (whereby you request `--thing a b c`), I've converted all the existing pid parameters (and filled them in where they were missing) in all the existing plugins.  Could the plugin authors people review and check that their plugins all look good and work properly?  My hope is to commit this in 7 days if not sooner...
> Plugins: Convert existing plugins over to use a list for PIDs

- volatility/framework/automagic/linux.py
- volatility/framework/automagic/mac.py
- volatility/framework/plugins/linux/lsof.py
- volatility/framework/plugins/mac/check_syscall.py
- volatility/framework/plugins/mac/check_sysctl.py
- volatility/framework/plugins/mac/check_trap_table.py
- volatility/framework/plugins/mac/ifconfig.py
- volatility/framework/plugins/mac/lsof.py
- volatility/framework/plugins/mac/netstat.py
- volatility/framework/plugins/mac/timers.py
- volatility/framework/plugins/mac/trustedbsd.py
- volatility/framework/symbols/linux/__init__.py
- volatility/framework/symbols/linux/extensions/__init__.py
- volatility/framework/symbols/mac/__init__.py
Refactor the Utilities classes as discussed at the most recent call.Refactor the Utilities classes as discussed at the most recent call.
> Refactor nix utilities

- volatility/framework/automagic/linux.py
- volatility/framework/automagic/mac.py
- volatility/framework/automagic/symbol_finder.py
Having chatted to Nick, I think the metadata being only for use within automagic and not saved when a configuration written is ok.  here's my attempt.  Any reviews are appreciated.  5:)
Closes issue #233
> Issue 233 mac aslr shift

- volatility/framework/configuration/requirements.py
- volatility/framework/interfaces/configuration.py
- volatility/framework/interfaces/layers.py
- volatility/framework/interfaces/plugins.py
- volatility/framework/plugins/windows/vadyarascan.py
- volatility/framework/plugins/yarascan.py
This refactors common yara tasks, so we can use the plugin versioning to
keep track of changes to the YaraScanner class.
Should be straightforward, just putting it up for review.  If there's no quibbles I'll merge it in a few days, only review if you feel like it.  5:)
> Yarascan: Move most of yarascanning into a versionable plugin

- volatility/framework/automagic/linux.py
- volatility/framework/constants/linux/__init__.py
- volatility/framework/plugins/linux/tty_check.py
- volatility/framework/symbols/linux/__init__.py
- volatility/framework/symbols/linux/extensions/__init__.py
Also added some infrastructure for kernel tracking needed for plugin
> Created linux_tty_check plugin

- volatility/framework/plugins/linux/check_idt.py
not ready for merge. plugin currently is not finding the module names for each entry in idt table. Just wanted to get this opened so any other issues that may need to be fixed can be addressed now.
> created linux_check_idt

- volatility/framework/symbols/__init__.py
Fixes #279.
Previously (because symbol types aren't necessarily named) we generated them directly from the JSON, which could mean that an array of `randomtype`, return an array with a `ReferenceTemplate` rather than the appropriately looked up type.
This solution ensures that (like `get_type`) the subresolution of the symbol's type occurs when the symbol is requested.
Note: this still allows local tables to have a type or symbol request made, and to return a type that includes a `ReferenceTemplate`.  Since this could refer to a type outside of the existing table (or one that hasn't yet been encountered, and which itself contains a `ReferenceTemplate`), we don't resolve these in local tables.
I think this is a better way of handling the problem than my first attempt (having the symbol …
> Symbols: Resolve symbols returned from symbol_space.get_symbol

- volatility/framework/plugins/windows/memdump.py
- volatility/framework/plugins/windows/memmap.py
Changes suggested from first pull request.
Memdump outputs to pid.offset.dmp rather than pid.dmp
> Stephanie's memdump & memmap plugin

- volatility/framework/plugins/windows/strings.py
had a problem with the break statement of the while loop.
Changed the progress bar update to once every 0.1 % for efficiency.
> Strings bugfix + progress bar efficiency 

- volatility/framework/symbols/intermed.py
This fixes anonymous flattening issues (#291), handling any level of nested anonymous types.
> Fix #291. It supports any level of depth of nested anonymous types.

- volatility/framework/plugins/windows/cmdline.py
- volatility/framework/plugins/windows/psscan.py
Option "--pid" added to psscan.py
> pid filter added to psscan.py

- volatility/framework/symbols/windows/extensions/__init__.py
fix get_sids function in broken images
> fix get_sids function

- volatility/framework/plugins/windows/privileges.py
> privileges plugin

- volatility/framework/plugins/windows/envars.py
> envars plugin

- volatility/framework/layers/crash.py
- volatility/framework/symbols/windows/crash64.json
Add in crashdump64 support.  Handles the new bitmap format (I dunno whether DumpType = 1 happens in CrashDump64 files).  All looks pretty straight forward, so I'm happy to commit in 7 days if no one shouts...
Closes #196
> Crashdump64

- volatility/framework/symbols/windows/extensions/pool.py
Ok, I think this improves the poolscanning (and certainly, resolves the issue with symlinkscan on an image where I could recreate it).  I'll give it the full 7 days for review, but will commit it after that if there's no comments by then...  5:)
Closes #278
> Windows: Add PointerCount check to improve poolscanning

- volatility/framework/plugins/windows/psscan.py
fix: the bounce from physical to virtual process is required only for OS < Win10.
Added the check in the "dump" option.
> OS check for physical to virtual

- volatility/cli/volshell/generic.py
Add a couple useful functions to volshell
> Volshell: Make it easier to make configurables

- volatility3/framework/objects/__init__.py
> Objects: Avoid reconstructing pointed objects

- volatility3/framework/__init__.py
This should add support to pick up plugin bundles, so that users can just drop a zip file into their plugins directory, rather than needing to unpack files and put them in the right places (particularly helpful for plugins that come with their own JSON files).  It could do with a review/kicking the tyres, etc. though...
> Plugin zips
