volatilityfoundation/volatility3

volatility/cli/__init__.py
Fixes issue #104.
I can't think of any issues, and POSIX defines stderr to be for diagnostics output as well as for errors.  This is also where all our logging messages go, so seems like it should be ok.  I'm not sure who else should review this, so I'll just merge this, but this information is in case that was the wrong move.  5;)
=> CLI: Move progress output to stderr from stdout.

volatility/framework/plugins/windows/vadyarascan.py
This patch ensures we scan the vad segments within the correct layer
(the process layer, not the kernel layer) and lists the pid in the
output.
Just for confirmation, asking @iMHLv2 for a quick review.  I'll commit this on the 31st October if I don't hear any objections...  5;)
=> vadyarascan: Ensure we scan the right layer

volatility/framework/plugins/windows/cmdline.py, volatility/framework/plugins/windows/dlldump.py, volatility/framework/plugins/windows/malfind.py, volatility/framework/plugins/windows/moddump.py, volatility/framework/plugins/windows/procdump.py, volatility/framework/plugins/windows/strings.py, volatility/framework/plugins/windows/svcscan.py, volatility/framework/plugins/windows/vaddump.py, volatility/framework/plugins/windows/verinfo.py
There were a number of issues with commit 3df5e995 that was applied in
haste (notably, that exceptions wasn't imported in several cases, which
would break the code if it were ever run).
We now give debugging output when a process can't be constructed and
provide as much available information as possible and/or have merged several try/excepts into a single one (to reduce costs of setting up the try block).
Two unused lines were also removed from verinfo.
=> Fix a logging on add_process_layer exceptions.

volatility/plugins/linux/__init__.py, volatility/plugins/mac/__init__.py, volatility/plugins/windows/__init__.py, volatility/plugins/windows/registry/__init__.py
Previously if submodules were imported after the plugin/symbol __path__s had
been set, it would only use the __path__s from the constants module.
We now use the parent module's __path__s to ensure we get the right
sub__path__s.
This seems better/more flexible than changing the original constants
(since they'd no longer be constant) and allows people more chance to
override things.  It brings with it potential confusion as a local
plugin directory will need __init__ files with this magic to allow the
core modules to run (since they come first in the path list).
This should be unnoticeable by most, but is a fairly big change so could do with discussion (I'm pretty sure the code works fine, it's more if there's a better way of handling things so that the plugin path can be overridden the …
=> Ensure we use configured paths at import.

volatility/framework/symbols/intermed.py
Hi, I was looking at the code for managing symbols and found this line:
https://github.com/volatilityfoundation/volatility3/blob/master/volatility/framework/symbols/intermed.py#L372
I think there might be a semantic inconsistency there: the ‘end_bit’ keyword is populated with the bit_length of the field, instead of the end_bit.
I have looked at the symbol json file, and it seems that bitfields contain ‘start_bit’ and ‘bit_length’. On the contrary, volatility2 vtypes seem to represent bitfields with their ‘start_bit’ and ‘end_bit’. (E.g.: https://github.com/volatilityfoundation/volatility/blob/aa6b960c1077e447bda9d64df507ec02f8fcc958/volatility/plugins/overlays/windows/win2003_sp0_x86_vtypes.py#L1814)
Given that the BitField class on framework/objects/_ _ init _ .py stores start_bit and …
=> Fix on 'end_bit' computation

volatility/framework/layers/msf.py, volatility/framework/layers/registry.py, volatility/framework/objects/__init__.py, volatility/framework/plugins/mac/bash.py, volatility/framework/plugins/mac/psaux.py, volatility/framework/plugins/mac/pslist.py, volatility/framework/plugins/mac/tasks.py, volatility/framework/plugins/windows/callbacks.py, volatility/framework/plugins/windows/handles.py, volatility/framework/plugins/windows/malfind.py, volatility/framework/symbols/windows/extensions/__init__.py
This makes the layer `is_valid` method a little more robust.
Coverts all calls to is_valid to boolean checks (any exceptions thrown now should likely still be thrown and/or should be caught by the is_valid method).
Adds some lengths in where the liable length is known.
Removes checks that are already wrapped in a try/except call (there's no point doing the check if we're still going to catch an exception for something else).
This feels like it could potentially trip something up, so not putting a merge deadline on this.
=> Is valid exception catching

volatility/framework/automagic/linux.py, volatility/framework/automagic/mac.py, volatility/framework/automagic/windows.py, volatility/framework/layers/crash.py, volatility/framework/layers/intel.py, volatility/framework/layers/lime.py, volatility/framework/layers/physical.py, volatility/framework/layers/vmware.py
Rejig the ordering for stackers.  Ensures the (slow) Wintel/Linux/Mac stackers aren't attempted until simpler (header check) lower layers are tested.
This is pretty small, but I figured I'd make a pull request just in case anything crops up...
=> Improve stacking

volatility/framework/layers/resources.py, volatility/framework/symbols/windows/pdbconv.py
This ensures all downloading happens through the `ResourceAccessor` class, and improves a few points:
* Dealing with SSL errors
* Incorrect percentage calculations
* Repeated listing of available handlers
* Try the most common option first
I'll merge this on the 20th unless anyone shouts...
=> Improve downloading

volatility/framework/symbols/windows/extensions/__init__.py
It seems that Windows symbols sometimes represent the DirectoryTableBase in KPROCESS as an array, others as an unsigned long, others as an unsigned long long. This fix deals with these discrepancies in the is_valid method for the EPROCESS class, just like it is done in the add_process_layer method.
=> Fix on eprocess is_valid

volatility/cli/__init__.py, volatility/cli/text_renderer.py
This ensures that renderers like CSV and the upcoming JSON renderer don't output the title line in stdout, but that all other plugins do output it as a normal part of the output.
=> CLI: Don't output the title for structured output.

volatility/framework/symbols/windows/extensions/__init__.py
This PR adds functions init_order_modules and mem_order_modules, equivalent to load_order_modules for the other 2 linked lists present in the PEB. I don't know if these where intentionally excluded, but since the equivalents were present in volatility2 and I was using them in PyREBox, I just added them to the class.
=> Add init_order_modules and mem_order_modules to EPROCESS class

volatility/framework/plugins/windows/poolscanner.py, volatility/framework/symbols/windows/__init__.py, volatility/framework/symbols/windows/extensions/__init__.py, volatility/framework/symbols/windows/extensions/pool.py
This shifts reorganizes the pool header code and moves the check for an object's header type matching the pool header's `object_type` from the pool header's `get_object` to the calling plugin's pool traversal code.
It should be noted that this changes the pool header code, and we'll need to bump something somewhere to tell plugins whether they can or can't use that code.  The main version is really intended for the UI to check, having a single plugin_api version would require all other plugins to bump their required versions before they'd be interoperable with this version.  Breaking down the components so that each has its own API number would be difficult to define what's part of which component.  That's a separate discussion that needs to happen though.
This will need some work on the …
=> Move poolscan typecheck

volatility/framework/plugins/yarascan.py
Fixes issue #107.
The eventual path we chose was to leave the generic yarascan to work only on kernel space, and for each OS to implement its own process space scanners.
=> Yarascan: Make generic yarascan just scan kernel memory.

volatility/framework/interfaces/objects.py, volatility/framework/symbols/windows/extensions/__init__.py, volatility/framework/symbols/windows/extensions/kdbg.py, volatility/framework/symbols/windows/extensions/pe.py
The only place we were using this was to get the table to look up its name and then use it to construct a new object (based on the previous object's table and a new type name) at a different offset.  This would cause us to do an unnecessary table lookup each time, when what we really wanted (the table name) had already been determined.  This simplifies the API a little to just return the symbol's name.
Options for the future include:
* Changing the function to construct a new object based on the table of the previous
* Removing this as an unnecessary extravagence
* Adding additional convenience functions to further split the `.vol.type_name` down
* Breaking this up at object create to ensure `type_name` is always stored separately to `symbol_table_name`, but this would be reasonably …
=> Objects: Simplify get_symbol_table to get_symbol_table_name.

volatility/cli/text_renderer.py
This renderer will output a formatted/pretty-printed JSON output file.  It contains a nested tree structure (in particular for tree output) and makes use of a special `__children` field to do so.  We don't currently have strict checking on column names not starting with `__` but it seems like a remote possibility so for now I'm not including any special casing for it.
I'll probably merge this on the 7th unless someone shouts...
=> Add in JSON renderer

volatility/framework/plugins/windows/vaddump.py
This PR fixes an incorrect variable initialization in the VadDump module.
The out_of_range variable should be `vad.get_end()` instead of `vad_get_start() + vad.get_end()`. The typo must've come up when porting this module from volatility2 to volatility3 which originally was `out_of_range = vad.Start + vad.Length `.
This is causing the output files to be a lot heavier and containing extra unwanted data.
Therefore I just fixed this variable.
=> VadDump: Fix incorrect variable out_of_range in vad_dump

volatility/framework/plugins/windows/malfind.py
Creating a pull request to follow up on the conversation from #144
=> Use a kernel layer to read vad protection constants

volatility/framework/symbols/windows/services-win10-15063-x86.json, volatility/framework/symbols/windows/services-win10-16299-x86.json
The hand-written JSON types for 32-bit Windows 10 versions were missing the Tag member.
=> add Tag to 32-bit win10 service types

volatility/framework/contexts/__init__.py, volatility/framework/interfaces/objects.py, volatility/framework/objects/__init__.py
Ensures that `thing.vol.size` is appropriately set from the available information.
This also includes arrays (which can be dynamically sized).  The value for arrays is never taken from the Intermediate Symbol Format, but calculated based on the count and subtype and then stored.  It is updated whenever the count (that could change the size) is altered.  The subtype can only be altered by a recast, which should then recalculate the appropriate value.
This is important to get right, particularly if people are reliant on it, so it won't get pushed without a review...
=> Object sizes

volatility/framework/layers/resources.py
On my Mac, I'm running Python 3.6.3 from python.org. The commit 2d3cceda only solved the problem halfway for me. This PR fixes the rest. In particular, the ssl shipped with my Python version doesn't have `ssl.SSLCertVerificationError`. Instead, it raises `ssl.SSLError` with a reason of `CERTIFICATE_VERIFY_FAILED`.
=> ResourceAccessor: fix unverified retrieval for ssl.SSLError

volatility/framework/plugins/windows/svcscan.py
This is a cleanup and re-submission of https://github.com/volatilityfoundation/volatility3/pull/149
In particular, the changes include:
*  removes the redundant fallback checks for `ObHeaderCookie`
* add a new distinguisher for 15063,  using `x == (10, 0, 15063)`
* win10 before 15063 uses win8 types
* when possible, keep the fallback checks in order
=> svcscan cleanup: win10 before 15063 uses win8 types

volatility/framework/symbols/mac/extensions/__init__.py
As of commit `d7f5a13c467878e7927fe55c8ba7b28a3fc56e77`, buildbot broke on the mac tasks test.  Looking at the change, I thought this was because `not filter_func(proc)` could be checked if `proc` were invalid (hence adding `fda64dde958c6e236ca099b52fcce88884ad13b0`).
It turns out that due to the fix, it no longer stops as soon as it hits an error (meaning the next item in the queue is requested, which is where the break actually happened).  There was exception handling around the first item read of `next` or `prev`, but not around the later attempts to access the next item.  I've extended the exception handling around each of the loops, and then optimized it so that the loop code isn't duplicated but parameterized instead.
Please could you check that this behaves as you'd expect, and if …
=> Issue mac tasks

volatility/framework/symbols/windows/extensions/__init__.py
Catch more exceptions when traversing Windows VADs. In particular, catch `InvalidAddressException` on the LeftChild and RightChild separately, so an exception on one doesn't prevent traversing the other. Log exceptions in either case. I observed this issue when trying to parse VADs for a terminated process.
=> catch more exceptions traversing windows vads

volatility/framework/symbols/windows/pdbconv.py
Don't filter out functions which begin with `__imp` since these functions are separate from their "full" version. The SSDT often points to the `__imp` functions in Windows 10.
Fixes #184
=> pdbconv: save _imp functions in JSON

volatility/framework/automagic/windows.py
Reorder the DTB tests, since 64-bits have more to match and are likely
more common these days.  We've had an instance where a 32-bit DTB was
detected because of a self-referential pointer over a 64-bit DTB leading
to an inaccessible image.
This fixes issue #193.
=> Wintel: Reorder the DTB tests

volatility/framework/automagic/pdbscan.py, volatility/framework/interfaces/layers.py, volatility/framework/layers/crash.py, volatility/framework/layers/elf.py, volatility/framework/layers/intel.py, volatility/framework/layers/lime.py, volatility/framework/layers/linear.py, volatility/framework/layers/msf.py, volatility/framework/layers/registry.py, volatility/framework/layers/segmented.py, volatility/framework/layers/vmware.py, volatility/framework/plugins/windows/pslist.py, volatility/framework/plugins/windows/pstree.py, volatility/framework/plugins/windows/strings.py, volatility/plugins/windows/statistics.py
This adds support for NonLinearlyMapped layers (ones where the domain vector doesn't translate directly to a vector of the same length in the range of the function).
It makes some reasonably deep changes (notably, the _scan_iterator that returns chunks of space to scan need to know the domain size, not just the range size of the chunks it gets, so segments must maintain, for linear ones the last two fields of a segment are always identical, but for non-linear they may not be).
This also adds decode/encode functions to all translation layers where data read at the range's vector can be decoded to fill the domain vector provided.
I'd very much like this reviewed (a fair amount) because it's pretty deep in the core.  Things to check for are:
* Efficiency (has this slowed things down …
=> Non linear support

volatility/framework/automagic/linux.py
The commit a6cd344e223f8f306bd3c81ddec6acf53c6d8c62 broke ASLR shift determination for Linux. Due to the new call chain that eventually invokes `LinuxUtilities.find_aslr()`, this function receives two `cls` arguments, while it only expects one. All positional arguments are shifted by one: For example, the second erroneous `cls` argument ends up at the position of the `context` argument and therefore `LinuxUtilities.find_aslr()` fails. The first three arguments (`cls`, `context` and `symbol_table`) of `LinuxUtilities.find_aslr()` are:
```
<class 'volatility.framework.automagic.linux.LinuxUtilities'>
<volatility.framework.automagic.linux.LinuxSymbolFinder object at 0x7f30c53049d0>
<volatility.framework.contexts.Context object at 0x7f30c6a1ddf0>
```
I believe the root cause is the newly …
=> Fix find_aslr() function invocation for Linux.

volatility/framework/automagic/symbol_finder.py, volatility/framework/interfaces/symbols.py, volatility/framework/symbols/__init__.py, volatility/framework/symbols/intermed.py
With 573590878afde184df443e581110a84a4ee4583f, the computed ASLR shift is now applied in the `get_symbol()` function of the respective `ISFormatTable` subclass. Furthermore, symbols that are looked up via `get_symbol()` are cached. This leads to a problem if symbols get resolved (and cached) at a point in time where ASLR shift computation was not executed yet. For me, this happens when I try to run the command listed below (after applying #235).
This leads to `init_task` and `files_task` already being resolved and cached with the default ASLR shift of 0, when ASLR shift is computed. Subsequently, the memory accesses required for `linux.pslist.PsList` fail, as they involve the symbol `init_task`. If you want to showcase this caching issue, you can inspect the cache at this position: …
=> Clear symbol cache after ASLR computation on Linux.

volatility/cli/volshell/generic.py
Currently, the db(..) commands in volshell will print a wrong offset:
(primary) >>> db(0xffff81a000e0)
0xffff81a000f0    4c 69 6e 75 78 20 76 65 72 73 69 6f 6e 20 34 2e    Linux.version.4.
0xffff81a00100    34 2e 30 2d 31 32 34 2d 67 65 6e 65 72 69 63 20    4.0-124-generic.
(the data is actually from offset ...e0, but the offset shown in the left column is off by 0x10)
This pull request fixed this issue by incrementing offset only after it was printed, not before.
=> print correct db/.. offset: increment offset after printing, not before

volatility/cli/__init__.py, volatility/framework/automagic/__init__.py, volatility/framework/automagic/stacker.py
Ok,
So it occurred to me that the LayerStacker automagic was a little non-generic and not really reusable.  Previous it look a single_location parameter that was a URI and attempted to stack as high as possible on top of, and then attach it to the configuration at a TranslationRequirement that wasn't yet satisified.
It seemed as though the "construct layers" code could be applied to any starting layer, rather than taking an explicit URI and always starting from a physical layer.  It also occurs to me that people may want to apply it without a requirement/config tree beside it.  That's surprisingly hard to arrange with the existing system, since it all gets built in a temporary context which is thrown away if it's not attached to a requirement in the original context, so I think I'm gonna …
=> Refactor stacker automagic

volatility/framework/constants/__init__.py, volatility/framework/interfaces/objects.py
Adds in the new `has_valid_member` capability, bumping the API for plugins that might use it.  All plugins should now have the `_required_framework_version` member, which should be set to a tuple of (1,1,0) for those that need to use this feature.
=> Has valid member

volatility/cli/__init__.py, volatility/framework/automagic/linux.py, volatility/framework/automagic/mac.py, volatility/framework/automagic/stacker.py, volatility/framework/automagic/windows.py, volatility/framework/interfaces/automagic.py
This will significantly speed up mac and linux plugins by not running the Wintel stacker uselessly against such plugins.  It also allows CLI users to choose which stackers to use, should they so desire, and allows generic plugins to still try all the stacking options.
This is built on top of #244, which should be reviewed/get committed first...
=> Configurable stacker list

volatility/cli/text_renderer.py, volatility/framework/plugins/windows/registry/printkey.py, volatility/framework/renderers/conversion.py, volatility/framework/renderers/format_hints.py, volatility/framework/symbols/windows/extensions/registry.py
Here's a partial resolution to ensuring the registry API returns all data, but hints that it's likely to be a string (and leaves it to the renderer to determine how to render it).  Any renderer that does not support the StrLike hint will display the bytes instead.
=> Registry stringlike data

volatility/framework/plugins/windows/poolscanner.py
Pool alignments appear dependent on system architecture. This update checks for the current apparent system architecture and changes the alignment.
```
$ vol2.py -f win8x64_vm.dd --profile=Win8SP0x64 volshell
To get help, type 'hh()'
>>> addr_space = utils.load_as(self._config)
>>> obj.VolMagic(addr_space).PoolAlignment.v()
16
$ vol2.py -f win8x86_vm.dd --profile=Win8SP0x86 volshell
>>> addr_space = utils.load_as(self._config)
>>> obj.VolMagic(addr_space).PoolAlignment.v()
8
```
=> adds dynamic length of pool header alignments

volatility/framework/objects/__init__.py
Very quick one, just wanting views on the name for it (and whether it should be a property or a method, whose name would then start with a verb)?
I think `is_valid` is too generic and is already used in other contexts for readability of data, so I went with legal.  Also considered `valid_choice` as a property, but again valid without context isn't ideal.  5:S
Opinions and views welcomed, otherwise this'll go in in 7 days...  5:)
=> Objects: Add a convenience function for validating enum values

volatility/framework/plugins/windows/info.py
This will allow other plugins get easily get various kernel structures and information without having to implement too much themselves.
Mostly I'd like to check concept and names of method please.  I'll commit it in 7 days unless someone speaks up...
=> Windows.info: Refactor windows.info as classmethods

volatility/framework/plugins/windows/strings.py
Strings takes forever and there is no indication of progress.
1. Replaced readlines() with readline() to prevent loading the entire strings file to memory all at once.
2. Added process callback to indicate the progression.
3. Converted the re.compile of strings parse_line to global in order to prevent compilation for each line.
4. Changed the regex to not include the trailing newline (\n)
=> Improved strings efficiency

volatility/framework/plugins/linux/check_idt.py, volatility/framework/plugins/linux/keyboard_notifiers.py, volatility/framework/plugins/linux/lsof.py, volatility/framework/plugins/linux/tty_check.py, volatility/framework/plugins/mac/check_syscall.py, volatility/framework/plugins/mac/check_sysctl.py, volatility/framework/plugins/mac/check_trap_table.py, volatility/framework/plugins/mac/ifconfig.py, volatility/framework/plugins/mac/lsof.py, volatility/framework/plugins/mac/mount.py, volatility/framework/plugins/mac/netstat.py, volatility/framework/plugins/mac/timers.py, volatility/framework/plugins/mac/trustedbsd.py, volatility/framework/symbols/linux/__init__.py, volatility/framework/symbols/mac/__init__.py
This is designed to allow our utility classes to change without breaking plugins that depend on them (or at least, gracefully inform the user they've broken).  Since these are core plugins, we can generally keep these in check (and there is a question about whether these are parts of the framework and therefore could be lumped into part of the `_required_framework_version`, but that number would skyrocket, and this allows us a little more granularity.
Asking for reviews by @atcuno because it touches mac/linux and from @npetroni to make sure the idea/level of granularity seems appropriate (some overcatch, but not so much as a different version of the framework for each change).
This isn't overly contentious though, so I'll commit it in 4 days unless someone shouts...  5:)
=> Plugins: Version Mac/LinuxUtilities classes

volatility/framework/plugins/windows/cmdline.py
Added method "get_cmdline" to be able to call the plugin on a single process.
The general plugin behavior is exactly the same, just moved the "query" part in a
single method, callable from outside
=> CmdLine windows plugin: call on a single process added

volatility/framework/plugins/isfinfo.py
Add a new plugin to provide information about ISF files (both those that can be found automatically, and specific files), and tell us the number of various types/symbols/enums stored within.  This is designed to help us debug/diagnose issues with ISF files.
The design decisions I slightly question are:
* We don't lump the windows/linux/mac information into a single field, because that makes it more difficult to use/filter out again computationally (also, technically, one ISF could hold multiple of these fields at once)
* Filter is only done on the URL, not on the linux/mac banner (because those must be read from the file before filtering can happen, implying a cost of every filter to even filter it
* I've chosen `--isf` because I think `--file` would be more confusing for users given `-f` …
=> Plugin: Add initial version of ISFinfo plugin

volatility/framework/plugins/windows/vadinfo.py
Right now the default is set to 0 (no limit) as opposed to Vol2 where it is set to 1GB.
=> Added maxsize option to vadinfo as optional parameter, as in Vol2.

volatility/framework/plugins/mac/lsmod.py, volatility/framework/plugins/mac/malfind.py, volatility/framework/plugins/mac/proc_maps.py
A quick fix to strings that didn't make sense.
=> Change bad copy/descriptions for Mac that say Linux

volatility/framework/plugins/windows/dlllist.py
This should address #333. In particular, there's no need to catch `AttributeError` if we're already using `dll_load_time_field` which limits accesses to only the Windows versions that have the member.
=> refs #333 catch InvalidAddressException instead of AttributeError when accessing DLL timestamps

volatility/framework/interfaces/configuration.py, volatility/framework/interfaces/plugins.py
This feels like the right direction.   Since we're essentially using dictionaries, I think supporting None values rather than an entry not existing makes sense, both will need checking when attempting to access something from the config, but None is much easier to check.  I can only imagine this impacting code that a) assumes value in the config means it must always be a valid value or b) that in some way uses None to indicate information.  If we run into any such circumstances, I figure we'll correct them then rather than worrying over the possibilities now.  This has been around for a while, and should be easy to roll back if necessary, so I'll merge this as is.
Closes #324
=> Plugins: Allow None types in the configuration tree as values

volatility/framework/plugins/windows/verinfo.py
This accesses DllBase in a try/except to handle cases where the member is invalid/paged. This does not fix #332, but it addresses another issue I found when researching #332.
=> refs #332 catch invalid address exceptions when reading DllBase

volatility/framework/plugins/windows/vadinfo.py
In one of the earlier commits the varible was erased from being passed to vaddump - that corrects it.
=> Fix 'maxsize variable doing nothing' bug

volatility/framework/symbols/windows/pdbutil.py
This rebuilds the pefile appropriately and extracts the necessary debugging information.
Fixes #382
=> PDBUtility: fix get_guid_from_mz

volatility/framework/plugins/windows/netscan.py, volatility/framework/symbols/windows/extensions/network.py, volatility/framework/symbols/windows/netscan-win10-16299-x64.json, volatility/framework/symbols/windows/netscan-win10-17134-x64.json, volatility/framework/symbols/windows/netscan-win10-17134-x86.json, volatility/framework/symbols/windows/netscan-win10-17763-x64.json, volatility/framework/symbols/windows/netscan-win10-18363-x64.json, volatility/framework/symbols/windows/netscan-win10-19041-x64.json, volatility/framework/symbols/windows/netscan-win10-19041-x86.json, volatility/framework/symbols/windows/netscan-win10-x86.json, volatility/framework/symbols/windows/versions.py
Fixes a few things for `netscan`.
- the symbol table is chosen based on the newest one available for the given Windows version not just for Win10, but for older versions as well (>= Vista)
- fixes bug which can occur when trying to dereference a nullpointer actually works because the image has a valid virtual memory address of `0`, which happened to me in exactly one memory image of 30. Honestly no idea how often this will happen...
- adds a bunch of new symbol tables for different Windows versions, including the change for Win10x64_18363 found by @mikevsunny in https://github.com/volatilityfoundation/volatility/issues/763. This obviously does not fix the issue that 18363 is not properly detected, but one step after the other :)
Note: …
=> Netscan fixes

volatility/framework/objects/__init__.py
When working on volshell, just getting the standard object repr kinda always requires an extra step to get information about the object.  This provides most of it up-front.  I've opted for only ever returning common data for all objects (mostly just structs and arrays), but we *could* change the output to include for example the array count (although technically the size will give that way) and things like the array's subtype/target.  I think I'm happy at this level, but as always, open for review...  5:)
=> Objects: Make repr(object) more useful

volatility/framework/automagic/windows.py
The DTB finder test returns a full DTB, if that's over the scan chunk
size it'll get discarded, so we remove that test.
This is a small hotfix, and shouldn't have major consequences, but you never know.  Again, mostly waiting on the workflow discussion to happen.
=> Automagic: Windows DTB finder was too limited

volatility/framework/symbols/mac/extensions/__init__.py
Spotted this, not sure if there's other instances of it, but might be worth a think if there's any other clearly similar locations where a pointer dereference from scanned objects situation might occur.  5:)
I'll merge it once you're happy with it (and the workflow discussion's happened).
=> Linux: Use native_layer when constructing from a pointer offset

volatility/framework/plugins/windows/netlist.py, volatility/framework/plugins/windows/netscan.py, volatility/framework/plugins/windows/netstat.py, volatility/framework/symbols/windows/extensions/network.py, volatility/framework/symbols/windows/netscan-win10-15063-x64.json, volatility/framework/symbols/windows/netscan-win10-15063-x86.json, volatility/framework/symbols/windows/netscan-win10-16299-x64.json, volatility/framework/symbols/windows/netscan-win10-17134-x64.json, volatility/framework/symbols/windows/netscan-win10-17763-x64.json, volatility/framework/symbols/windows/netscan-win10-18362-x64.json, volatility/framework/symbols/windows/netscan-win10-18363-x64.json, volatility/framework/symbols/windows/netscan-win10-19041-x64.json, volatility/framework/symbols/windows/netscan-win10-x86.json, volatility/framework/symbols/windows/netscan-win7-x64.json, volatility/framework/symbols/windows/netscan-win7-x86.json
This plugin parses the "official" tcpip.sys kernel structures to find network connections, similar to what `netstat` does. 
~It is named `netlist` because it is to `netscan` what `pslist` is to `psscan`.~ Renamed to `netstat` for consistency :)
It finds...
- TCP Endpoints by parsing the TCP Partition Table (see _The Art of Memory Forensics_, chapter 11)
- UDP Endpoints by parsing the UDP port pool
- TCP Listeners by parsing the TCP port pool
It depends on some requirements:
- the given image must have its `tcpip.sys` PE image headers accessible in memory to fetch the PDB GUID (this has worked for every image I have tested this with, so I consider this given)
- the offsets must be correct, but that of course is required for every plugin with custom objects ;)
This plugin is of course way …
=> Netstat for x64 Windows

doc/source/glossary.rst, doc/source/index.rst
This is an attempt to add some definitions and terms, so that everybody uses the same nomenclature and knows how to refer to particular elements/aspects within the volatility world.  Happy for any changes (hence the review), but ideally this will be the place we define things that people can refer to for clarification of names.
@npetroni You seem best placed to look this over, please let me know if I've been inaccurate (almost certain) or even whaaaay off (entirely possible) with some of my definitions and/or if there's any important ones I've missed.
The concept is not necessarily to link every time we use one of these words in the rest of the documentation, but this is a possibility should we desire it...
=> Documentation: Add an initial glossary
